# Generated by Django 3.2.5 on 2022-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_image', models.ImageField(blank=True, default='', upload_to='ios_img')),
                ('android_image', models.ImageField(blank=True, default='', upload_to='android_img')),
                ('win_image', models.ImageField(blank=True, default='', upload_to='win_img')),
                ('mac_image', models.ImageField(blank=True, default='', upload_to='mac_img')),
                ('linux_image', models.ImageField(blank=True, default='', upload_to='linux_img')),
                ('name', models.TextField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
